version: '3'

services:

  pcatalog:
    build: 
      context: .
      dockerfile: Dockerfile
  
  postgres:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_DB: kaufland
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    ports:
      - '5432:5432'
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data:
